### ISSUE TITLE
Need some input validation and beauty css for my first web project

### ISSUE THREAD

**Issue by gibunamesk** [gibunamesk/Signupform#1]

**Comment by gibunamesk** [comment]
Need some input validation and beauty css for my first web project. This is the first time I come to html css and I need some help <333

**Comment by thinhb1901951** [comment]
I think I can help with this, I am working on a FOSS exercise and I feel interesting in your project. I think I can do something if you assign me :>

**Comment by gibunamesk** [comment]
I'm glad to see your reply so quickly. Sure, I love if you can help, you can join now. This is the first time I am working on a web project, and I am starting from a small module.

**Comment by thinhb1901951** [comment]
Thankss. I'm working on it :>

**Comment by gibunamesk** [comment]
Thank a lot for your help my friendd
